### DISCUSSION TITLE
archives/Hexo/41513

### DISCUSSION THREAD

**Discussion by giscus** [4rozeN/4rozeN.github.io#10] [General]
# archives/Hexo/41513

方案 hexo 博客默认是没有代码折叠功能的，如果需要实现代码折叠功能，需要安装 hexo-sliding-spoiler 库或者借助 Hexo 过滤器功能。  hexo-sliding-spoiler 使用 Hexo 过滤器实现代码折叠 By Kiyan   hexo-sliding-spoiler 实现代码折叠  hexo-sliding-spoiler 提供 demo 演示：https

https://4rozen.github.io/archives/Hexo/41513.html

**Comment by youyeyejie** [comment]
您好，想请问代码块太长的时候，折叠下半部分是怎么实现的呢

**Reply by 4rozeN** [reply]
这实际上是我更换shiki插件作为代码高亮引擎后发现的折叠功能，我本来没打算用这个插件实现折叠，但是这个插件自带了折叠代码功能。本文中更换代码渲染器给出的项目地址就是我目前正在使用的，你可以按照项目的说明文档进行配置，代码折叠功能项在这个插件里实际是`highlight_height_limit`项，超出此项设定的高度则将代码折叠。如果不想更换的话，那么使用Hexo提供的过滤器功能也能实现折叠。

**Reply by 4rozeN** [reply]
抱歉，可能是我的文章没有写清楚，现在我已将文章进行了编辑并更新。

**Reply by youyeyejie** [reply]
感谢答复！还有一个问题是下方折叠的按钮和折叠处的透明度应该怎么调整，我目前的显示效果非常不明显

**Reply by 4rozeN** [reply]
这个问题可以借助自定义css功能实现。
具体来说，你需要在你的hexo博客根目录下的source文件夹下创建css文件夹，并在这个css文件夹中创建`.css`文件，最后在`_config.fluid.yml`中的`custom_css`项中进行引用，否则自定义css文件将不会起作用。
具体的代码实现，可以借助浏览器开发者工具对你想要修改的元素进行选取，得到对应元素的类名然后编写对应的css样式得到。如果你不熟悉前端，可以借助AI帮助你完成或者参考我的样式：
```css
.markdown-body code,
.markdown-body pre {
  font-family: "Fira Code", monospace !important;
  line-height: 1 !important;
}

/* 以下样式给 shiki 代码块使用 */
.code-expand-btn i {
  color: #bbc4d5 !important; /* 展开或隐藏代码块的按钮颜色 */
}
:root {
  --hlnumber-color: #a5a5a5 !important; /* 行号颜色 */
  --hl-bg: #1f1f1f !important; /* 代码块背景颜色 */
  --hlnumber-bg: #1f1f1f !important; /* 行号背景颜色 */
}
figure.shiki .codeblock pre * {
  font-family: 'Fira Code', 'Noto Sans SC' !important;
}
pre code {
  color: #b9b9b9; /* 没有颜色方案的代码语言的表现色 */
}

```
