### ISSUE TITLE
友链申请

### ISSUE THREAD

**Issue by 4rozeN** [4rozeN/4rozeN.github.io#9]
### 友链要求：

- 您的网站应保持一定简洁度，避免过多广告或推广信息
- 您的网站应具有良好的稳定性和可靠性
- 您不应当恶意构造攻击链接或钓鱼链接

### 本站信息：

- 网站名称：4rozeN
- 网站描述：C0d1ng noob自进阶
- 网站地址：https://4rozen.github.io
- 网站图标：https://4rozen.github.io/favicon.ico

申请友链格式与如下：

```yaml
{
  title: "4rozeN",
  intro: "C0d1ng noob自进阶",
  link: "https://4rozen.github.io",
  avatar: "https://4rozen.github.io/favicon.ico"
}
```

实际上，对于本站的描述我并不在意，可任写（非恶意向描述都可以）。

- C0d1ng noob自进阶
- W0rk ? L1f3.p3nd1ng : M1nd.cl34rC4ch3
- ...
